# Learning NumPy
🎵do you wanna learn some NumPy?🎵

🎵yes I wanna learn some NumPy🎵

In [2]:
# 导入numpy


import numpy

In [3]:
# 基础
# 一些基本的数组操作


# 创建数组
array = numpy.array([[1, 2, 3], [3, 4, 5]])

print(f'数组的形状：{array.shape}')
print(f'数组的维度：{array.ndim}')


# 索引数组的方式和原版Python列表一样：把序号写在方括号里，只不过是把所有axes的序号一次性用元组传进去
print(f'第一排第二列的元素：{array[1, 2]}')


# 可以通过numpy.arange来生成一个区间的数组（比如numpy.arange(10, 20)就是[10, 11, 12... 19]）
array = numpy.arange(10)


# 用':'可以切出一段数组。以下例子中是切出第5位 (包括) 直到第7位 (不包括)
print(array[5:7])

数组的形状：(2, 3)
数组的维度：2
第一排第二列的元素：5
[5 6]


In [13]:
# 更多的数组切割

array = numpy.array([[1, 2, 3], [3, 4, 5], [7, 8, 9]])

print(f'切取从(0, 0)到(1, 1)的2*2数组：\n{array[:2, :2]}\n')


# 可以用同样的方法设置一个N维区间内的元素
new_array = numpy.array([[0, 1], [2, 3]])
array[1:, 1:] = new_array
print(f'右下角2x2区间被更改后的数组：\n{array}')

切取从(0, 0)到(1, 1)的2*2数组：
[[1 2]
 [3 4]]

右下角2x2区间被更改后的数组：
[[1 2 3]
 [3 0 1]
 [7 2 3]]


array([2, 0])

In [5]:
# 奇奇怪怪的数组创建

all_ones = numpy.ones((3, 4)) # 创建一个3 * 4的元素全是1的数组
all_zeros = numpy.zeros((5, 6)) # 创建一个5 * 6的元素全是0的数组
full_array = numpy.full((3, 3), 5) # 前一个参数定义数组大小，后一个定义用什么值填满数组

identity_matrix = numpy.identity(5) # 生成单位矩阵


# 随机数呀随机数

random_sample_array = numpy.random.random_sample((5, 6)) # 生成的数字是在[0, 1]之间均匀分布的
standard_normal_array = numpy.random.standard_normal((3, 4)) # 生成的数字是在[-1, 1]之间正态分布的

print(random_sample_array)
print()
print(standard_normal_array)

# 注：numpy.random.random_sample和numpy.random.rand作用一样；
# numpy.random.standard_normal和numpy.random.randn作用一样
# 两种情况下后者都是前者的缩写，但是由于后者的参数是以多个数字参数传入数组大小（而不是通过一个元组传入），
# 并和正常的numpy函数的规范不统一（导致新学员可能记不住），所以这里推荐用前者，也就是全称

[[0.13753459 0.66127025 0.55283352 0.79879536 0.1769448  0.9902032 ]
 [0.29254933 0.28587036 0.36362998 0.51411815 0.52300157 0.97445813]
 [0.70059418 0.28607801 0.80311043 0.57326683 0.072048   0.09378123]
 [0.17612835 0.46862831 0.31578869 0.57890243 0.33827781 0.81864549]
 [0.71496115 0.94985957 0.72296645 0.81738155 0.44101912 0.99751334]]

[[ 1.59790309  1.19245598  1.15531617 -0.10535981]
 [-1.08207114  0.40089801 -0.5498108  -1.09429291]
 [-0.27152594 -0.10835256 -0.11905613  0.82643379]]


In [6]:
# 更多数组操作


# 拷贝并延长一段数组（延长的维度必须是一个已经存在的维度）
# 延长时所使用的数组、延长后的数组、延长后的数组的每一个循环的部分均是不同的内存
array = numpy.array([[1, 2, 3]])
repeated_array = numpy.repeat(array, 3, axis=0)


# 如何拷贝数组
arxiv = numpy.array([10, 20, 30])

my_program = arxiv # 这样的话两个变量指向的还是同一个值
print(my_program is arxiv) # True

my_paper = arxiv.copy() # 拷贝整个array的值
print(my_paper is arxiv) # False

True
False


In [7]:
# 数学操作


array = numpy.array([1, 2, 3])

print(f'基础加法: {array} + 1 = {array + 1}\n')
print(f'乘法和次方是基于每个元素的: {array} ** 2 = {array ** 2}\n')
print(f'点乘: {array} ⋅ {array} = {array.dot(array)}\n')
print(f'位运算: {array} << 2 = {array << 2}')

基础加法: [1 2 3] + 1 = [2 3 4]

乘法和次方是基于每个元素的: [1 2 3] ** 2 = [1 4 9]

点乘: [1 2 3] ⋅ [1 2 3] = 14

位运算: [1 2 3] << 2 = [ 4  8 12]


In [8]:
# 数组元素挑选方式


array = numpy.arange(10)
print(f'复习一下numpy.arange：{array}')

# 在判断语句中比较数组和单个数字元素会返回一个和原数组大小一样的布尔数组
# 布尔数组里的每个元素意味着原数组在这个位置下的值在判断中是否为True
print(f'数组哪些位置上的元素大于5：{array > 5}')
# 元素大于5的位置上是True，而其余位置上是False

# 再举个例子
print(f'数组哪些位置上的元素是偶数：{array & 1 == 0}')

# 用一个形状相同的布尔数组来索引一个数组会返回一个只包含在布尔数组里为True的位置上的值的数组
# 和上面的方式相结合，可以轻易过滤出一个数组里符合判断的元素
print(f'数组里所有大于5的元素：{array[array > 5]}')
print(f'数组里所有是偶数的元素：{array[array & 1 == 0]}')

复习一下numpy.arange：[0 1 2 3 4 5 6 7 8 9]
数组哪些位置上的元素大于5：[False False False False False False  True  True  True  True]
数组哪些位置上的元素是偶数：[ True False  True False  True False  True False  True False]
数组里所有大于5的元素：[6 7 8 9]
数组里所有是偶数的元素：[0 2 4 6 8]


In [9]:
# 批量处理


# BTW数组里还可以包含字符... 虽然基本上永远不会用到
char_array = numpy.array(list('曼哈顿曼哈顿！！'))
print(char_array)

print(f'复习一下Python-把字符转换成unicode：A -> {ord("A")}')
vectorize = numpy.vectorize(ord)
unicode_array = vectorize(char_array)
print(unicode_array)

# numpy.vectorize的返回值（vectorize object）会把传入的参数直接扔进创建时所给的function
# 用法和Python的map很像，只不过是遵循NumPy的broadcast规则

# 再举个复杂点的例子（所有偶数除以N；所有奇数平方）
N = 2
array = numpy.arange(10)
vectorize_func = numpy.vectorize(lambda a, b: a ** 2 if a & 1 == 1 else a / b)
print(vectorize_func(array, N))

['曼' '哈' '顿' '曼' '哈' '顿' '！' '！']
复习一下Python-把字符转换成unicode：A -> 65
[26364 21704 39039 26364 21704 39039 65281 65281]
[ 0.  1.  1.  9.  2. 25.  3. 49.  4. 81.]
