# LearningPyTorch
🎵do you wanna learn some PyTorch?🎵

🎵yes I wanna learn some PyTorch🎵

In [16]:
# dependencies

import torch
import numpy as np

## `torch` package
这个部分会含括`torch`的基本数学功能，比如张量和张量操作。

In [17]:
# 张量（tensor）是一个任何维度的数组/矩阵（和numpy的array差不多）

tensor = torch.tensor([1, 2, 3])
tensor_2d = torch.tensor([[1, 2], [3, 4]])

print(f'an exmaple of tensor: \n{tensor}\n')
print(f'an example of a 2D tensor: \n{tensor_2d}')

an exmaple of tensor: 
tensor([1, 2, 3])

an example of a 2D tensor: 
tensor([[1, 2],
        [3, 4]])


In [82]:
# 张量可以被用于数学运算

tensor = torch.tensor([1, 2, 3])

print(f'基础加法: {tensor} + 1 = {tensor + 1}\n')
print(f'乘法和次方是基于每个元素的: {tensor} ** 2 = {tensor ** 2}\n')
print(f'点乘: {tensor} ⋅ {tensor} = {tensor.dot(tensor)}\n')
print(f'位运算: {tensor} << 2 = {tensor << 2}')

基础加法: tensor([1, 2, 3]) + 1 = tensor([2, 3, 4])

乘法和次方是基于每个元素的: tensor([1, 2, 3]) ** 2 = tensor([1, 4, 9])

点乘: tensor([1, 2, 3]) ⋅ tensor([1, 2, 3]) = 14

位运算: tensor([1, 2, 3]) << 2 = tensor([ 4,  8, 12])


In [48]:
# 张量这个类里还有一些实用的函数

# 正常情况下，这些函数的运算结果（一个新的张量）会被函数返回；但是，当在个别函数名后加上
# 下划线（‘_’），函数的运算结果则会覆盖原来的变量的值，并返回该变量。

# 没有‘_’
tensor = torch.tensor([49, 529, 682]) # my favorite SCPs (owo)
result = tensor.add(98)
print(f'original tensor after operation: {tensor}')
print(f'results: {result}\n')
# 运算后原张量的值不变

# 有‘_’
tensor = torch.tensor([2, 3, 5, 7, 11])
result = tensor.add_(100)
print(f'original tensor after operation: {tensor}')
print(f'results: {result}\n')
# 现在，result和tensor指向的object是同一个

original tensor after operation: tensor([ 49, 529, 682])
results: tensor([147, 627, 780])

original tensor after operation: tensor([102, 103, 105, 107, 111])
results: tensor([102, 103, 105, 107, 111])



In [89]:
# 想获取关于一个张量的信息也很容易

tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(f'获取一个张量的元素的数量：{torch.numel(tensor)}')
print(f'获取一个张量的形状：{tensor.shape}')
# 获取形状用tensor.size()也可以，并且在转换成字节码后没有区别，但是不推荐
# 原因是tensor.shape更贴近于numpy的风格，而numpy的风格正在逐渐转换成行业规范

获取一个张量的元素的数量：6
获取一个张量的形状：torch.Size([2, 3])


In [91]:
# 创建张量的方式有很多，之前的代码中也有torch.tensor的调用方法

# Python列表式
tensor = torch.tensor([1, 2, 3])
print(tensor)

# NumPy数组式
array = np.array([[1, 2], [3, 4]])
tensor = torch.tensor(array)
print(tensor)

# 注意：torch.tensor是对传入的参数进行深拷贝（不一定是真正意义上的深拷贝，但是效果一样）后创建新的
# 张量。对新创建的张量进行改动不会影响原来的张量，并且用torch.tensor创建张量的时间复杂度至少O(N)。

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])


# 拓展
这部分中大部分的函数都是用在torch内部的（或是用于基于torch的库），并不会在Intro to ML课程中特别用到。假如对torch内部不感兴趣的学员可以跳过这一段。

In [70]:
# 一些关于tensor的属性和操作

tensor = torch.tensor([1, 2, 3])

# 判断一个变量是否为torch的张量
torch.is_tensor(tensor) # True
torch.is_tensor([2, 3, 4]) # False 

# 判断一个变量是否为torch的储存类型
# torch的储存类型通常是一个继承_StorageBase和与自己对应的C底层类的子类
torch.is_storage(torch.DoubleStorage()) # True
torch.is_storage(tensor) # False
# 储存类型并不携带任何semantics

False

In [77]:
# 改变tensor默认的float dtype （data type）

print(f'tensor默认的float dtype是float32: {torch.tensor([1.0, 2.0]).dtype}\n')

# 把默认改成float64
torch.set_default_dtype(torch.float64)

print(f'更改之后的dtype: {torch.tensor([1.0, 2.0]).dtype}')

tensor默认的float dtype是float32: torch.float64

更改之后的dtype: torch.float64


## Autograd是什么
这段可能难度稍微高一些，并且以后的课上也会有详细的讲解。假如学员阅读这一段有困难则可以跳过。

`TODO: actually write this part`