# LearningPyTorch
What do you call a pie that caught on fire in the oven?

__A Py-Torch.__

In [7]:
# dependencies

import torch
import numpy as np

## `torch` package
这个部分会含括`torch`的基本数学功能，比如张量和张量操作。

In [3]:
# 张量（tensor）是一个任何维度的数组/矩阵（和numpy的array差不多）

tensor = torch.tensor([1, 2, 3])
tensor_2d = torch.tensor([[1, 2], [3, 4]])

print(f'一个一维张量：\n{tensor}\n')
print(f'一个二维张量：\n{tensor_2d}')

一个一维张量：
tensor([1, 2, 3])

一个二维张量：
tensor([[1, 2],
        [3, 4]])


In [4]:
# 张量可以被用于数学运算

tensor = torch.tensor([1, 2, 3])

print(f'基础加法: {tensor} + 1 = {tensor + 1}\n')
print(f'乘法和次方是基于每个元素的: {tensor} ** 2 = {tensor ** 2}\n')
print(f'点乘: {tensor} ⋅ {tensor} = {tensor.dot(tensor)}\n')
print(f'位运算: {tensor} << 2 = {tensor << 2}')

基础加法: tensor([1, 2, 3]) + 1 = tensor([2, 3, 4])

乘法和次方是基于每个元素的: tensor([1, 2, 3]) ** 2 = tensor([1, 4, 9])

点乘: tensor([1, 2, 3]) ⋅ tensor([1, 2, 3]) = 14

位运算: tensor([1, 2, 3]) << 2 = tensor([ 4,  8, 12])


In [5]:
# 张量这个类里还有一些实用的函数

# 正常情况下，这些函数的运算结果（一个新的张量）会被函数返回；但是，当在个别函数名后加上
# 下划线（‘_’），函数的运算结果则会覆盖原来的变量的值，并返回该变量。

# 没有‘_’
tensor = torch.tensor([49, 529, 682]) # my favorite SCPs (owo)
result = tensor.add(100)
print(f'操作之后原来的张量：{tensor}')
print(f'操作的结果：{result}\n')
# 运算后原来的张量的值不变

# 有‘_’
tensor = torch.tensor([49, 529, 682])
result = tensor.add_(100)
print(f'操作之后原来的张量：{tensor}')
print(f'操作的结果：{result}\n')
# 现在，result和tensor指向的object是同一个

操作之后原来的张量：tensor([ 49, 529, 682])
操作的结果：tensor([149, 629, 782])

操作之后原来的张量：tensor([149, 629, 782])
操作的结果：tensor([149, 629, 782])



In [6]:
# 想获取关于一个张量的信息也很容易

tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(f'获取一个张量的元素的数量：{torch.numel(tensor)}')
print(f'获取一个张量的形状：{tensor.shape}')
# 获取形状用tensor.size()也可以，并且在与运算相关的字节码上没有区别，但是不推荐，
# 因为tensor.shape更贴近于numpy的风格，而numpy的风格正在逐渐转换成行业规范

获取一个张量的元素的数量：6
获取一个张量的形状：torch.Size([2, 3])


In [26]:
# 创建张量的方式有很多，之前的代码中也有torch.tensor的调用方法

# Python列表式
tensor = torch.tensor([1, 2, 3])
print(tensor)

# NumPy数组式
array = np.array([[1, 2], [3, 4]])
tensor = torch.tensor(array)
print(tensor)

# 注意：torch.tensor是对传入的参数进行拷贝后创建新的张量
# 对新创建的张量进行改动不会影响原来的张量，并且用torch.tensor创建张量的时间复杂度至少O(N)

# 假设想在不进行拷贝的情况下通过NumPy数组建立张量，可以使用torch.as_tensor
array = np.array([1, 2, 3])
tensor = torch.as_tensor(array)
tensor[0] = 100
print(f'对张量的操作会反映在NumPy数组里：{array}')

# 还可以复制一个张量
tensor = torch.tensor([5, 6, 7])
new_tensor = tensor.clone().detach() # detach会把张量从原来的graph中脱离（详细请见autograd实现方式）

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
对张量的操作会反映在NumPy数组里：[100   2   3]


In [34]:
# 张量的转换

tensor = torch.tensor([1, 2, 3])
single_value_tensor = torch.tensor(5.0)

print(f'转化成NumPy数组：{tensor.numpy()}')
print(f'转化成Python列表：{tensor.tolist()}')
print(f'从单个元素张量里获取元素的值：{single_value_tensor.item()}')

转化成NumPy数组：[1 2 3]
转化成Python列表：[1, 2, 3]
从单个元素张量里获取元素的值：5.0


In [54]:
# 快捷创建张量

# 标明[起点, 终点)、以及每次增加的step，可以生成从起点到终点，并每个元素之间增加step的张量
#（长度为(end - start) / step）
print(f'从1到2，并每次增加0.2：{torch.arange(1, 2, 0.2)}\n')
# torch.arange和torch.range作用一样，但是后者已经deprecated

# 标明[起点, 终点]、以及总共元素的数量(steps)，可以生成在该范围内均匀分布的steps个元素的张量
print(f'从10到20之间均匀分布的5个点：{torch.linspace(10, 20, 5)}\n')

# 生成二维的identity矩阵
print(f'5 * 5的identity矩阵：\n{torch.eye(5)}\n')

# 生成全是某个值的张量
print(f'全是99.5：\n{torch.full((2, 3, 2), 99.5)}\n')

# 生成全是0或1的张量
print(f'全是0：\n{torch.zeros((2, 3))}')
print(f'全是1：\n{torch.zeros((2, 3))}')
# 虽然在有torch.fill的基础上，这两个函数看起来没有什么存在的意义，但是zeros和ones是从NumPy
# 中演变出来的习俗，所以挺酷的

从1到2，并每次增加0.2：tensor([1.0000, 1.2000, 1.4000, 1.6000, 1.8000])

从10到20之间均匀分布的5个点：tensor([10.0000, 12.5000, 15.0000, 17.5000, 20.0000])

5 * 5的identity矩阵：
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

全是99.5：
tensor([[[99.5000, 99.5000],
         [99.5000, 99.5000],
         [99.5000, 99.5000]],

        [[99.5000, 99.5000],
         [99.5000, 99.5000],
         [99.5000, 99.5000]]])

全是0：
tensor([[0., 0., 0.],
        [0., 0., 0.]])
全是1：
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 拓展
这部分中大部分的函数都是用在torch内部的（或是用于基于torch的库），并不会在Intro to ML课程中特别用到。假如对torch内部不感兴趣的学员可以跳过这一段。

In [ ]:
# 一些关于tensor的属性和操作

tensor = torch.tensor([1, 2, 3])

# 判断一个变量是否为torch的张量
torch.is_tensor(tensor) # True
torch.is_tensor([2, 3, 4]) # False 

# 判断一个变量是否为torch的储存类型
# torch的储存类型通常是一个继承_StorageBase和与自己对应的C底层类的子类
torch.is_storage(torch.DoubleStorage()) # True
torch.is_storage(tensor) # False
# 储存类型并不携带任何semantics

In [25]:
# 改变tensor默认的float dtype （data type）

print(f'tensor默认的float dtype是float32: {torch.tensor([1.0, 2.0]).dtype}\n')

# 把默认改成float64
torch.set_default_dtype(torch.float64)

print(f'更改之后的dtype: {torch.tensor([1.0, 2.0]).dtype}')

False